/* The SHORT versions of INP's written answers (26 Sep 2026, his rule: estate memory "saq-short-answers"). Every written
   question in this bank is the tool's, and so is its full model answer (content/authored/, each naming its deck and slide);
   a full answer packs three to five facts into a line, and nobody recalls that cold. So each one is cut here into short
   lines, one fact a line, grouped under the question's own parts, with a memory hook. Gated by shorts.mjs: every **bold**
   word must be in the step (`of`) it is cut from, every step needs a line, a line is at most 14 words. Order = the order
   the quiz rows are listed on the page. */
const G = (q, ...facts) => ({ q, facts: facts.map(([t, of, fix]) => (fix ? { t, of, fix } : { t, of })) });

export const SHORTS = [
  /* ── Discharge Planning ── */
  { quiz: 'a-discharge', k: 'define discharge planning', title: 'Discharge planning: definition and benefits',
    hook: 'It starts on admission day, and it keeps people from coming back.',
    groups: [
      G('Define it',
        ['An **interdisciplinary** approach to **continuity of care**', 0],
        ['It helps the person **move smoothly** from one setting to another', 0],
        ['It keeps the **progress already made**, and it **begins at admission**', 0]),
      G('Two benefits',
        ['**Fewer readmissions**', 1],
        ['A **shorter length of hospital stay**', 1],
        ['**Less follow-up community care** needed', 1],
        ['Or: they leave **understanding their medicines** and the **warning signs**', 2]),
    ] },
  { quiz: 'a-discharge', k: 'mr lear', title: 'Mr Lear’s discharge plan: four things',
    hook: 'Medicines, wound, walking, and who helps him at home.',
    groups: [
      G('1 · Medicines',
        ['**Medicines**: what he goes home with, **how and when** to take them', 0],
        ['What to do if the **pain increases**', 0]),
      G('2 · The wound',
        ['A **District Nurse referral** to monitor it and **change dressings**', 1],
        ['Teach the **signs of infection** and **who to contact**', 1]),
      G('3 · Falls risk',
        ['A **physiotherapy review** before discharge: safe on stairs? a **mobility aid**?', 2],
        ['**Home safety**', 2]),
      G('4 · Support at home',
        ['Can he **cook, shop and shower**?', 3],
        ['**Involve his daughter** (with his **consent**) or set up **home care**', 3],
        ['Arrange **transport home** and **follow-up appointments**', 3]),
    ] },
  { quiz: 'a-discharge', k: 'list four items', title: 'What a written discharge summary contains',
    hook: 'How they leave, how to look after themselves, what to watch for, what they may do, when to come back.',
    groups: [
      G('Any four, one mark each',
        ['The **mode of discharge**: walking, wheelchair, stretcher', 0],
        ['**Instructions for self-care**: medicines, diet, wound care, pain', 0],
        ['The **signs and symptoms of complications** or drug reactions', 1],
        ['… and the **action to take**', 1],
        ['**Permissible activities** (lifting, driving)', 2],
        ['The **correct settings** for any **equipment**', 2],
        ['**Follow-up** instructions and **appointments**', 3],
        ['What to do if it goes wrong: **emergency procedures**, in plain language', 3]),
    ] },

  /* ── Family-centred Care ── */
  { quiz: 'a-fcc', k: 'name the three elements', title: 'Family-centred care: the three elements',
    hook: 'R-P-T: Relationship, Participation, Tailoring.',
    groups: [
      G('1 · Relationship',
        ['**Relationship**: a **mutually respectful partnership**', 0],
        ['Action: **invest time in building trust**', 0]),
      G('2 · Participation',
        ['**Participation and involvement** that respects their **autonomy**', 1],
        ['Action: **involve them in care**; find out **what is important** to them', 1]),
      G('3 · Tailoring care',
        ['**Tailoring care** to their **needs, strengths**, limits and context', 2],
        ['Action: help them make **informed decisions**; plan **realistic** care', 2]),
    ] },
  { quiz: 'a-fcc', k: 'state three situations', title: 'When health information may go to family',
    hook: 'A family history, a progress update, a danger.',
    groups: [
      G('Three situations',
        ['Collecting a **family or genetic history**', 0],
        ['Telling **close relatives** the patient’s **presence, condition and progress**', 1],
        ['… unless the **patient has vetoed** it', 1],
        ['A **serious threat** to anyone’s **health or safety** (abuse, self-harm)', 2]),
    ] },

  /* ── Pain Assessment ── */
  { quiz: 'a-pain', k: 'oldcarts', title: 'OLDCARTS pain assessment',
    hook: 'OLD CARTS: say the eight letters, then the word each one starts.',
    groups: [
      G('The eight letters',
        ['O · **Onset**: when did it start?', 0],
        ['L · **Location**: where is it? does it **radiate**?', 0],
        ['D · **Duration**: how long? does it come and go?', 1],
        ['C · **Characteristics**: what does it feel like?', 1],
        ['A · **Aggravating factors**: what makes it worse?', 2],
        ['R · **Relieving factors**: what makes it better?', 2],
        ['T · **Timing**: pattern or frequency, day or night', 3],
        ['S · **Severity**: rated on a **pain scale**, 0–10, at rest and moving', 3]),
    ] },
  { quiz: 'a-pain', k: 'distinguish nociceptive', title: 'Nociceptive vs neuropathic pain',
    hook: 'Nociceptive: damaged TISSUE, normal wiring. Neuropathic: damaged WIRING.',
    groups: [
      G('Nociceptive',
        ['Cause: **damage to somatic or visceral tissue**', 0],
        ['It fires the **normal pain pathway**: cuts, fractures, burns, post-op', 0],
        ['Somatic feels **localised, sharp, aching, throbbing**', 1],
        ['Visceral feels **diffuse or referred**, **crampy**, colicky', 1]),
      G('Neuropathic',
        ['Cause: **injury, lesion or dysfunction** of the **nervous system**', 2],
        ['Stimuli are **processed abnormally**: diabetes, shingles, MS', 2],
        ['Feels **burning, shooting, stabbing**, **electric-shock-like**', 3],
        ['**Numbness**; **pain on light touch**', 3]),
    ] },
  { quiz: 'a-pain', k: 'give two voluntary', title: 'Responses to pain, and must they show?',
    hook: 'What they DO, what their BODY does, and pain is what the person says it is.',
    groups: [
      G('Voluntary (behavioural), any two',
        ['**Moving away** from the painful stimulus', 0],
        ['**Grimacing, moaning, crying**; **restlessness**', 0],
        ['**Guarding**: protecting the area, refusing to move', 0]),
      G('Involuntary (physiological), any two',
        ['Sympathetic: **raised BP, pulse** and breathing rate; **dilated pupils**', 1],
        ['Parasympathetic: **nausea and vomiting**, **fainting**, lowered BP', 1]),
      G('Must they show these signs?',
        ['**No**: pain is **subjective**, **what the person says it is**', 2],
        ['Some are **stoic** or **whakamā**, so the **absence of signs** is not proof', 2]),
    ] },

  /* ── Written section · Process & assessment ── */
  { quiz: 'w-care', k: 'list the five steps of the nursing', title: 'The nursing process, five steps',
    hook: 'ADPIE: Assess, Diagnose, Plan, Implement, Evaluate, then round again.',
    groups: [
      G('The five steps, in order',
        ['1 **Assessment**: **collect data** by observation, interview, examination', 0],
        ['… **subjective and objective**; validate and document it', 0],
        ['2 **Diagnosis**: **actual and potential problems**, **prioritised**', 1],
        ['… written as **diagnostic statements**, not a medical diagnosis', 1],
        ['3 **Planning**: **patient-centred goals**, outcome criteria, a **time frame**', 2],
        ['4 **Implementation**: the **interventions are carried out**, **evidence-based**, safe', 3],
        ['5 **Evaluation**: the **patient’s response**; goal **met, partially met or not met**', 4],
        ['The process is **ongoing and cyclical**', 4]),
    ] },
  { quiz: 'w-care', k: 'explain how a nursing diagnosis', title: 'Nursing vs medical diagnosis',
    hook: 'Medical names the DISEASE; nursing names the RESPONSE. Problem + r/t + AEB.',
    groups: [
      G('How they differ',
        ['Medical diagnosis: the **disease or condition**', 0],
        ['Nursing diagnosis: the patient’s **actual or potential response** to it', 0],
        ['… managed by **independent nursing interventions**', 0]),
      G('The three parts of the statement',
        ['The **problem** (from the **NANDA-I** list)', 1],
        ['**Related to** the **aetiology** (its cause)', 1],
        ['**As evidenced by** the **signs and symptoms**', 1],
        ['e.g. **Nausea related to appendicitis**, as evidenced by pallor, sweating', 2]),
    ] },
  { quiz: 'w-care', k: 'patient centred goals', title: 'SMART goals',
    hook: 'SMART, and every goal is about the PATIENT, not the nurse.',
    groups: [
      G('What each letter stands for',
        ['S · **Specific**: states clearly what is to be achieved', 0],
        ['M · **Measurable**: **quantifiable** (Bristol stool type 3 or 4)', 1],
        ['A · **Achievable** with the **resources available**', 2],
        ['R · **Realistic**: possible for **this patient**', 3],
        ['T · **Timed**: a **time limit** (e.g. within 12 hours)', 4],
        ['The goal describes **patient behaviour**, not nurse behaviour', 4]),
    ] },
  { quiz: 'w-care', k: 'evaluation is the last column', title: 'The evaluation column of a care plan',
    hook: 'Each intervention, one goal, three verdicts.',
    groups: [
      G('What is written there',
        ['An **evaluation statement** for **each intervention**: the patient’s response', 0],
        ['Each one **dated, timed and signed**', 0],
        ['**One overarching statement** about the **goal**', 1]),
      G('The three verdicts',
        ['**Met**: the response **matches or exceeds** the outcome criteria', 2],
        ['**Partially met**: behaviour is **beginning to change**', 2],
        ['**Not met**: **no progress**', 2]),
    ] },
  { quiz: 'w-care', k: 'define objective data', title: 'Objective and subjective data',
    hook: 'Objective = what YOU can see (signs). Subjective = what THEY feel (symptoms).',
    groups: [
      G('Objective data',
        ['**Observable and measurable** facts: **signs**', 0],
        ['e.g. **pallor**, **sweating**, a measured temperature, an observed vomit', 1]),
      G('Subjective data',
        ['What **only the patient can feel and describe**: **symptoms**', 2],
        ['e.g. **“I feel like I’m about to be sick”**, or **rating their nausea**', 3]),
    ] },
  { quiz: 'w-care', k: 'define holism', title: 'Holism and a holistic assessment',
    hook: 'Body, mind, people, spirit: all connected.',
    groups: [
      G('Define holism',
        ['From the Greek **holos**: whole', 0],
        ['**Body, mind, emotions and spirit** are **interconnected**', 0],
        ['So the nurse sees the **patient as a whole**, not just the problem', 0]),
      G('What the assessment covers',
        ['**Physical**: body systems, **ADLs**, **falls risk**, skin, sleep, diet', 1],
        ['**Psychological**: **cognition**, mental health, **stressors and coping**, pain', 2],
        ['**Social** (and cultural): **family situation**, community, finances, language', 3],
        ['**Spiritual**: **beliefs, values, meaning**; death and dying', 3],
        ['Each aspect **influences the others**', 3]),
    ] },
  { quiz: 'w-care', k: 'give the three reasons', title: 'Why nurses document: three reasons',
    hook: 'Legal, professional, communication. If it isn’t documented, it didn’t happen.',
    groups: [
      G('The three reasons',
        ['A **legal requirement**: a **legal document**, **evidence of your practice**', 0],
        ['“**If it isn’t documented, it didn’t happen**”', 0],
        ['A **professional responsibility**: **Nursing Council** standards, **Code of Conduct**', 1],
        ['Records **clear, accurate, legible, timely**; signed, dated, timed', 1],
        ['A **communication tool** across the **multi-disciplinary team**', 2],
        ['It spots problems **early** and supports **continuity of care**', 2]),
    ] },
  { quiz: 'w-care', k: 'a nurse writes an entry', title: 'Correcting a documentation error',
    hook: 'One line, still readable, signed. Never white-out.',
    groups: [
      G('How to correct it',
        ['Cross it out with **one line** so the **original can still be read**', 0],
        ['Note that it is an **error** and **sign it**', 0],
        ['**Never erase** it or use **white out**', 0]),
      G('Two other don’ts (any two)',
        ['Don’t **rely on memory** or **leave blank spaces**', 1],
        ['Don’t write **on behalf of another** professional, or use **unapproved abbreviations**', 1],
        ['Don’t add late notes without marking them **retrospective**', 2],
        ['Don’t write **condition unchanged**, **assumptions** or **judgemental** language', 2]),
    ] },
  { quiz: 'w-care', k: 'ai det guides', title: 'AI²DET: the letters and why',
    hook: 'Acknowledge, Introduce, Identify, Duration, Explanation, Thank you.',
    groups: [
      G('What the letters stand for',
        ['A · **Acknowledge**; I · **Introduce**; I · **Identify**', 0],
        ['D · **Duration**; E · **Explanation**; T · **Thank you**', 1]),
      G('Why it was introduced',
        ['**Counties Manukau Health**, **2011**, by **Māori Health**', 2],
        ['After **patient complaints**: people were “**talking about us and not to us**”', 2]),
    ] },

  /* ── Written section · Clinical knowledge ── */
  { quiz: 'w-clin', k: 'a primary survey', title: 'The primary survey, A to E',
    hook: 'ABCDE: the order that kills fastest.',
    groups: [
      G('Each letter, and what you assess',
        ['A · **Airway**: **talking normally**? able to **cough**? anything **blocking** it?', 0],
        ['B · **Breathing**: **respiratory rate**, depth, **work of breathing**, **oxygen saturation**', 1],
        ['C · **Circulation**: **blood pressure and pulse**', 2],
        ['D · **Disability**: **level of consciousness**, **AVPU** or the **Glasgow Coma Scale**', 3],
        ['AVPU = **Alert**, responds to **Voice**, to **Pain**, **Unresponsive**', 3],
        ['E · **Exposure**: **temperature**', 4]),
    ] },
  { quiz: 'w-clin', k: 'give the normal adult ranges', title: 'Normal adult ranges',
    hook: 'Sats 95–100, BP 110–140 over 60–90, temp 36.5–37.5, pulse 60–100.',
    groups: [
      G('The normal ranges',
        ['**SpO2**: **95–100%**', 0],
        ['BP: **systolic** usually **110–140**, **diastolic** usually **60–90** mmHg', 1],
        ['Temperature: **36.5–37.5 °C**', 2],
        ['Above **38 °C** is **pyrexia**; below **35 °C** is **hypothermia**', 2]),
      G('Two definitions',
        ['**Tachycardia**: a heart rate **above 100** bpm', 3],
        ['**Bradycardia**: a heart rate **below 60** bpm', 3]),
    ] },
  { quiz: 'w-clin', k: 'what is the new zealand early warning', title: 'NZEWS: what, from what, what it triggers',
    hook: 'Score each sign 0–3, add them up, and the total calls for help.',
    groups: [
      G('What it is',
        ['A **safety tool** for adults who **acutely deteriorate** in hospital', 0],
        ['Each vital sign **scored 0–3**, higher the further from normal; **added** up', 0]),
      G('Calculated from seven measurements',
        ['**Respiratory rate**, **oxygen supplementation**, **oxygen saturation**', 1],
        ['**Heart rate**, **blood pressure** (systolic), **temperature**', 1],
        ['**Level of consciousness**', 1]),
      G('What it triggers',
        ['The total, or any **single significantly abnormal** sign (red or blue zone)', 2],
        ['… triggers an **escalating clinical response**', 2]),
    ] },
  { quiz: 'w-clin', k: 'define a healthcare associated', title: 'Healthcare-associated infection (HAI)',
    hook: 'Not there on arrival, shows up 48 hours later.',
    groups: [
      G('Define it',
        ['**Not apparent or incubating** at **admission**', 0],
        ['It appears **at least 48 hours after admission** (once called **nosocomial**)', 0],
        ['A main cause: **multi-drug resistant organisms**; up to **10%** of patients', 2]),
      G('Three common types',
        ['**Surgical site infection**; **urinary tract infection**', 1],
        ['**Pneumonia**; **bloodstream infection**', 1]),
    ] },
  { quiz: 'w-clin', k: 'name the six links', title: 'The chain of infection, six links',
    hook: 'Agent → Reservoir → Exit → Transmission → Entry → Host.',
    groups: [
      G('The six links, in order',
        ['1 **Infectious agent**: bacteria, viruses, fungi, protozoa', 0],
        ['2 **Reservoir**: where it survives (body, water, food, soil)', 1],
        ['3 **Portal of exit**: how it escapes (respiratory, GI, blood)', 2],
        ['4 **Mode of transmission**: contact, droplet, airborne, vector', 3],
        ['5 **Portal of entry**: how it gets in (mucous membranes, broken skin)', 4],
        ['6 **Susceptible host**: babies, the elderly, the unvaccinated', 5]),
    ] },
  { quiz: 'w-clin', k: 'define standard precautions', title: 'Standard vs transmission-based precautions',
    hook: 'Standard = everyone, always. Transmission-based = ADDED for a known bug.',
    groups: [
      G('Standard precautions',
        ['The **minimum** precautions for **all patients**', 0],
        ['Whenever **blood or body fluids** are possible: **you cannot tell by looking**', 0],
        ['e.g. **hand hygiene**, **PPE**, **safe sharps**, aseptic technique', 1]),
      G('Transmission-based, and the three types',
        ['**Added** for a **known or suspected pathogen**, by how it spreads', 2],
        ['**Contact**: MRSA, gastro', 3],
        ['**Droplet**: influenza, mumps', 3],
        ['**Airborne**: measles, TB; an **N95** and a **negative-pressure room**', 3]),
    ] },
  { quiz: 'w-clin', k: 'compare type 1 and type 2', title: 'Type 1 vs type 2 diabetes',
    hook: 'Type 1: NO insulin (auto-immune). Type 2: insulin doesn’t WORK (resistance).',
    groups: [
      G('Type 1',
        ['Cause: **auto-immune**; it destroys the **beta cells**, so **no insulin**', 0],
        ['About **5–10%** of people with diabetes; usually **under 40**', 0],
        ['Managed with **insulin therapy** and **blood glucose monitoring**', 1]),
      G('Type 2',
        ['Cause: **resistant to insulin**, or **secretes too little**', 2],
        ['Linked to **genetics, lifestyle** and **obesity**; about **90–95%**', 2],
        ['Managed with **diet control**, **physical activity**, **oral medicines**, maybe insulin', 3]),
    ] },
  { quiz: 'w-clin', k: 'define hypoglycaemia', title: 'Hypoglycaemia: definition, causes, symptoms',
    hook: 'Under 4 is the floor: too little food, or too much insulin.',
    groups: [
      G('Define it',
        ['Blood glucose **below 4 mmol/L**', 0]),
      G('Two causes',
        ['A **missed or delayed meal**; **too little carbohydrate**', 1],
        ['**Too much insulin**; exercise without adjusting; **alcohol**', 1]),
      G('Two symptoms',
        ['**Shaky, sweaty**; a **racing pulse**; **pale**', 2],
        ['**Tingling around the mouth**; suddenly **very hungry**; **headache**', 2]),
      G('Why it happens on insulin',
        ['Injected insulin **cannot be switched off**, so the level **keeps falling**', 3]),
    ] },
  { quiz: 'w-clin', k: 'define health literacy', title: 'Health literacy: two levels, three steps',
    hook: 'Find, understand, use. Then Ask, Build, Check.',
    groups: [
      G('The two levels',
        ['**Personal**: the ability to **find, understand and use** health information', 0],
        ['It is **not determined by intelligence**', 0],
        ['**Organisational**: how far organisations **equitably enable** people to do that', 1]),
      G('The three steps',
        ['**Ask**, **Build**, **Check**', 2],
        ['**Teach-back** is the **gold standard** for checking', 2]),
    ] },

  /* ── Community Needs Assessment ── */
  { quiz: 'a-cna', k: 'name the four steps of mcmurray', title: 'McMurray’s four steps',
    hook: 'Engage → Map → Analyse → Empower.',
    groups: [
      G('The four steps, in order',
        ['1 **Engage**: approach **key community members** (kaumātua, teachers)', 0],
        ['… **gain their consent**; be guided by their **perceptions and priorities**', 0],
        ['2 **Map**: the community’s **strengths, resources and risks**', 1],
        ['… with the **Social Determinants of Health Assessment Circle**', 1],
        ['3 **Analyse**: what is **helping or harming health** (e.g. a **SWOT**)', 2],
        ['4 **Empower**: **share the findings**; build **intervention strategies** with them', 3]),
    ] },
  { quiz: 'a-cna', k: 'what is a windscreen survey', title: 'The windscreen survey',
    hook: 'Drive through, look, take notes: your own eyes = primary data.',
    groups: [
      G('What it is',
        ['A quick **snapshot** of a community, by **driving through** and **observing**', 0],
        ['Aim: a general sense of its **strengths and needs**', 0]),
      G('Two things to look for',
        ['**Parks**, **schools**, **supermarkets and food access**', 1],
        ['**Housing conditions**, **transport**, **clinics** and pharmacies', 1]),
      G('Primary or secondary data?',
        ['**Primary data**: what **you observe yourself**', 2],
        ['It should then be **confirmed** with community groups and records', 2]),
    ] },
  { quiz: 'a-cna', k: 'a nurse analyses community', title: 'SWOT analysis of a community',
    hook: 'S and O help; W and T harm.',
    groups: [
      G('What each letter asks',
        ['**Strengths** (**helpful**): what is **working well**', 0],
        ['e.g. **strong whānau networks**', 0],
        ['**Weaknesses** (**harmful**): what is **harming health now**', 1],
        ['e.g. **limited GP access**, high deprivation', 1],
        ['**Opportunities** (**helpful**): **new services** or trends that could help', 2],
        ['e.g. **mobile health services**', 2],
        ['**Threats** (**harmful**): what could **arise** or **worsen inequities**', 3],
        ['e.g. **cost-of-living pressure**', 3]),
    ] },

  /* ── NZ Health Strategy 2023 ── */
  { quiz: 'a-nzhs', k: 'define health equity', title: 'Health equity vs equality',
    hook: 'Equality: the SAME for everyone. Equity: what each person NEEDS.',
    groups: [
      G('Define health equity',
        ['A **fair and just opportunity** to be **as healthy as possible**', 0],
        ['By **removing obstacles**: **poverty**, **discrimination**', 0]),
      G('How it differs from equality',
        ['**Equality**: everyone gets the **same resources**', 1],
        ['**Equity**: people get **what they need** to reach **similar outcomes**', 1]),
      G('One priority group',
        ['**Māori**, **Pacific peoples** or **disabled people**', 2],
        ['Equity rests on **ōritetanga** from **Te Tiriti o Waitangi**', 2]),
    ] },
  { quiz: 'a-nzhs', k: 'list the six priority areas', title: 'NZ Health Strategy 2023: six priorities',
    hook: 'Voice, flexible care, workforce, learning, a resilient system, partnerships.',
    groups: [
      G('The six priority areas',
        ['1 **Voice at the heart** of the system', 0],
        ['2 **Flexible, appropriate care**', 1],
        ['3 **Valuing our workforce**', 2],
        ['4 A **learning culture**', 3],
        ['5 A **resilient and sustainable system**', 4],
        ['6 **Partnerships for health and wellbeing**', 5]),
    ] },
  { quiz: 'a-nzhs', k: 'give three ways a nurse puts equity', title: 'Equity in everyday nursing practice',
    hook: 'See the barriers, speak up, practise safely.',
    groups: [
      G('Any three',
        ['Understand each patient’s **cultural, social and economic context**', 0],
        ['**Notice the barriers** that make it hard to get help', 0],
        ['**Advocate**: **speak up** for patients who face barriers', 1],
        ['Practise in a **culturally safe** way; uphold **Te Tiriti** principles', 2],
        ['Know your **unconscious bias**; **listen** so whānau **feel heard**', 2]),
    ] },

  /* ── Written section · Population health & equity ── */
  { quiz: 'w-pop', k: 'define the social determinants', title: 'Social determinants of health',
    hook: 'Where you are born, live, work and age shapes your health.',
    groups: [
      G('Define them',
        ['The conditions people are **born, grow, live, work and age** in', 0],
        ['They set **social position**: access to **power, money and resources**', 0],
        ['They account for **at least half** of health outcomes', 0]),
      G('Two examples, with the effect',
        ['**Housing**: **cold, damp, overcrowded** homes → **respiratory illness**', 1],
        ['**Food environments**: **food deserts** → **obesity**, **type 2 diabetes**', 1],
        ['**Work**: **insecure or unsafe** work → physical and **mental health risk**', 2],
        ['**Transport**: poor public transport **limits access** to care', 2]),
    ] },
  { quiz: 'w-pop', k: 'distinguish health inequality', title: 'Inequality, inequity and the social gradient',
    hook: 'Inequality = a difference. Inequity = an UNFAIR, avoidable difference.',
    groups: [
      G('The two terms',
        ['**Inequality**: **differences in health** between groups; **what**, not why', 0],
        ['**Inequity**: differences that are **unfair and avoidable**', 1],
        ['… from **systemic barriers**; **government policies** could reduce them', 1]),
      G('The social gradient',
        ['Health follows **socioeconomic position**, **step by step**', 2],
        ['The **lower** the position, the **worse the health**', 2]),
    ] },
  { quiz: 'w-pop', k: 'distinguish population health', title: 'Population health vs personal health',
    hook: 'Population = the GROUP. Personal = the ONE person.',
    groups: [
      G('The difference',
        ['**Population health**: a **group**’s outcomes, and how they’re **distributed**', 0],
        ['… and the **social, economic and environmental factors** behind them', 0],
        ['**Personal health**: **one individual’s** circumstances, risks, symptoms', 0]),
      G('One intervention at each level',
        ['Population: **national screening**, **community health campaigns**, **Healthy Homes**', 1],
        ['Personal: **direct patient care**; **one-to-one health education**', 2]),
    ] },
  { quiz: 'w-pop', k: 'the waitangi tribunal', title: 'Te Tiriti: the five health principles',
    hook: 'Self-determination, equity, active protection, options, partnership.',
    groups: [
      G('The five principles',
        ['**Tino rangatiratanga**: **self-determination**; Māori **lead** Māori health', 0],
        ['**Mana taurite**: **equity**, resources where **need is greatest**', 1],
        ['**Whakamarumarutia**: **active protection**; health is a **taonga**', 2],
        ['**Kōwhiringa**: **options**, including **kaupapa Māori services**', 3],
        ['**Pātuitanga**: **partnership** in planning, delivering and evaluating', 4],
        ['The old **“three Ps”** are **outdated**', 4]),
    ] },
  { quiz: 'w-pop', k: 'progress is the equity framework', title: 'PROGRESS: the equity framework',
    hook: 'Who benefits, who misses out: PROGRESS.',
    groups: [
      G('What it is for',
        ['A mnemonic for the **social factors** that shape **who gets sick**', 0],
        ['It asks **who is benefiting** and **who is missing out**', 0]),
      G('The letters',
        ['P **Place of residence**; R **Race / ethnicity** / culture', 1],
        ['O **Occupation**; G **Gender** / sex; R **Religion**', 2],
        ['E **Education**; S **Socioeconomic status**; S **Social capital**', 3]),
    ] },
  { quiz: 'w-pop', k: 'define demography', title: 'Demography and epidemiology',
    hook: 'Demography = the PEOPLE. Epidemiology = the DISEASE.',
    groups: [
      G('Define them',
        ['**Demography**: the **size, distribution and characteristics** of populations', 0],
        ['Demographers study **fertility**, **mortality**, **migration**', 0],
        ['**Epidemiology**: the **patterns, causes and control of disease** in groups', 1]),
    ] },
  { quiz: 'w-pop', k: 'name the three parts of the epidemiological', title: 'The epidemiological triangle',
    hook: 'Agent, host, environment: break one side and the disease stops.',
    groups: [
      G('The three parts, and how to break each',
        ['**Agent**: the **cause**; break it by **removing the agent** (medicine)', 0],
        ['**Host**: who gets sick; **protect the host**, e.g. **vaccination**', 1],
        ['**Environment**: what helps it **spread**; improve **hygiene and sanitation**', 2],
        ['Disease needs **all three**; **breaking any one** connection stops it', 3]),
    ] },
  { quiz: 'w-pop', k: 'define primordial', title: 'The four levels of prevention',
    hook: 'Before the risk, before the disease, catch it early, stop it worsening.',
    groups: [
      G('Each level, with an example',
        ['**Primordial**: stop **risk factors from developing**; e.g. **Healthy Homes Initiative**', 0],
        ['**Primary** (“**Prevent**”): **before the onset**; e.g. **vaccination**', 1],
        ['**Secondary** (“**Screen**”): **detect disease early**; e.g. **cervical screening**', 2],
        ['**Tertiary** (“**Treatment**”): stop it **worsening**; e.g. an **insulin regime**', 3]),
    ] },
  { quiz: 'w-pop', k: 'define epidemic', title: 'Epidemic and endemic',
    hook: 'Epidemic = MORE than expected. Endemic = always there, stable.',
    groups: [
      G('Define them',
        ['**Epidemic**: cases **in excess of what is normally expected**', 0],
        ['**Endemic**: a **relatively stable pattern** in an area or group', 1]),
    ] },

  /* ── Roles of Nurses ── */
  { quiz: 'a-roles', k: 'state what each part of the isbar', title: 'ISBAR: what each part stands for',
    hook: 'Who I am, what’s happening, what led here, what I think, what I want.',
    groups: [
      G('Each part, and what you say',
        ['I · **Introduction** / **Identify**: who and where you are, why calling', 0],
        ['S · **Situation**: what is happening **now**', 1],
        ['B · **Background**: what **led to** the situation', 2],
        ['A · **Assessment**: what you consider **the problem** to be', 3],
        ['R · **Request** / **Recommend**: what should be done', 4]),
    ] },
  { quiz: 'a-roles', k: 'define primary healthcare', title: 'Primary healthcare, and where nurses work',
    hook: 'Outside the hospital: where people live, work and play.',
    groups: [
      G('Define it',
        ['Healthcare **outside the hospital**', 0],
        ['Where clients **live, work and play**, **pre-birth to very old age**', 0]),
      G('Two examples',
        ['**District nursing**: in patients’ **homes**, or a clinic', 1],
        ['**Plunket** / **Well Child** clinics and home visits', 1],
        ['**General practice** nursing: immunisation, screening, **wound care**', 2],
        ['**School** or **workplace nursing**', 2]),
    ] },
  { quiz: 'a-roles', k: 'give three skills', title: 'Key skills for acute care nurses',
    hook: 'Spot it, say it, check who it is, teach, listen.',
    groups: [
      G('Any three',
        ['**Recognising and responding** to **patient deterioration**', 0],
        ['**Communicating assessment findings** (e.g. **ISBAR**)', 0],
        ['**Correct patient identification**', 1],
        ['**Health education**, especially **for discharge**', 1],
        ['Quickly **establishing rapport** and **really listening**', 2]),
    ] },

  /* ── Therapeutic Use of Self ── */
  { quiz: 'a-tus', k: 'name the five components', title: 'Emotional intelligence: five components',
    hook: 'Know yourself, manage yourself, drive yourself, feel for others, work with others.',
    groups: [
      G('The five components',
        ['**Self-awareness**: noticing **your own judgements** of patients', 0],
        ['**Self-regulation**: **managing your natural emotional responses**', 1],
        ['… this is **emotional labour**', 1],
        ['**Motivation**: driven by your **own values**, not **external reward**', 2],
        ['**Empathy**: seeing it from the **other person’s point of view**', 3],
        ['**Social skills**: **communicating**, **managing conflict**, collaborating', 4]),
    ] },
  { quiz: 'a-tus', k: 'define surface acting', title: 'Surface acting and deep acting',
    hook: 'Surface = a mask. Deep = a real change of heart.',
    groups: [
      G('Define them',
        ['**Surface acting**: **expressing an emotion you do not feel**', 0],
        ['“**Putting on a mask**”', 0],
        ['**Deep acting**: a **real shift in how the nurse feels**', 1],
        ['… reached by seeing it from the **patient’s perspective**', 1]),
      G('Which component?',
        ['Both are **emotional labour**, which belongs to **self-regulation**', 2]),
    ] },
  { quiz: 'a-tus', k: 'distinguish responsive', title: 'Responsive vs assertive communication',
    hook: 'Responsive: the SAME view (relationships). Assertive: DIFFERING views (advocacy).',
    groups: [
      G('Responsive',
        ['Builds understanding from the **same point of view**', 0],
        ['Used to **build relationships**', 0],
        ['e.g. **expressing empathy** to a frightened patient, and **listening**', 0]),
      G('Assertive',
        ['Understanding of **differing points of view**; used in **advocacy**', 1],
        ['e.g. **speaking up for the patient** to the team', 1]),
      G('Both',
        ['Skilled communicators **blend and balance both**', 2]),
    ] },

  /* ── Tikanga & Kawa Whakaruruhau ── */
  { quiz: 'a-tikanga', k: 'define kawa whakaruruhau', title: 'Kawa Whakaruruhau (cultural safety)',
    hook: 'The PATIENT decides whether the care was safe, not the nurse.',
    groups: [
      G('Define it',
        ['Care **judged safe by the recipient** of care', 0],
        ['Aim: **equitable outcomes for Māori**', 0]),
      G('Two things it requires',
        ['**Critical self-reflection**: how your **own biases** affect relationships', 1],
        ['Recognising and addressing **power imbalance**, **bias and racism**', 2],
        ['It goes **beyond cultural awareness**, sensitivity or competence', 2]),
    ] },
  { quiz: 'a-tikanga', k: 'define tapu and noa', title: 'Tapu and noa',
    hook: 'Tapu = set apart (protect it). Noa = ordinary (free of tapu).',
    groups: [
      G('Define them',
        ['**Tapu**: **sacred**, **restricted** or **set apart**', 0],
        ['Understood as **protective**: **safety and risk** precautions (Durie)', 0],
        ['**Noa**: **neutral, ordinary** or **unrestricted**', 1],
        ['Together they mark out **safe and unsafe practices**', 1]),
      G('One way to respect them',
        ['The **head** is **tapu**: **ask and explain before touching**', 2],
        ['Or: support **karakia**; protect **taonga**', 2]),
    ] },
  { quiz: 'a-tikanga', k: 'name three of the tikanga', title: 'Tikanga best practice: three principles',
    hook: 'Connect, include the whānau, respect what is precious.',
    groups: [
      G('Three principles, each with an action',
        ['**Whakawhanaungatanga**: build a **trusting relationship**', 0],
        ['Action: **introduce yourself**; **pronounce the person’s name correctly**', 0],
        ['**Whānau-centred care**: **shared decision-making**', 1],
        ['Action: **include whānau** where **consent** is given', 1],
        ['**Respect for tikanga and taonga**', 2],
        ['Action: support **karakia**; **ask rather than assume**', 2]),
    ] },

  /* ── Written section · Professional & legal ── */
  { quiz: 'w-prof', k: 'define informed consent', title: 'Informed consent and the two laws',
    hook: 'A PROCESS, not a signature. Code Right 7 + Bill of Rights s 11.',
    groups: [
      G('Define it',
        ['A **process** of communicating the **benefits, risks and alternatives**', 0],
        ['So the patient makes an **informed decision**: **more than a signature**', 0]),
      G('The two laws',
        ['The **Code of Health and Disability Services Consumers’ Rights**, **Right 7**', 1],
        ['The **Bill of Rights Act 1990**, **section 11**: the **right to refuse**', 2]),
    ] },
  { quiz: 'w-prof', k: 'list four pieces', title: 'What a patient must be told first',
    hook: 'What’s wrong, what we’ll do, what could happen, who, and what else.',
    groups: [
      G('Any four',
        ['The **diagnosis**, if known', 0],
        ['The **nature and purpose** of the treatment: what happens, what after', 0],
        ['Its **risks and benefits**', 1],
        ['**Who will be performing it**', 2],
        ['**Other options**, and the risks of **no treatment at all**', 3],
        ['All in a way they **can understand**; an **interpreter** if wanted', 3]),
    ] },
  { quiz: 'w-prof', k: 'who can give consent', title: 'Who can consent to treatment in NZ',
    hook: '16 and over: yourself. Under 16: a parent. Not competent: a guardian or attorney.',
    groups: [
      G('Each person',
        ['An adult: anyone **16 or over** can **consent to or refuse**', 0],
        ['A 14-year-old: a **parent, guardian** (or a **court order**)', 1],
        ['An adult **not competent**: a **legal guardian** or **enduring power of attorney**', 2],
        ['Still act in their **best interests**; find out **their views**', 2]),
    ] },
  { quiz: 'w-prof', k: 'describe the nurse s role', title: 'The nurse’s role in informed consent',
    hook: 'Advocate, check they understood, witness.',
    groups: [
      G('The role',
        ['**Advocate**: arrange an **interpreter** and **whānau support**', 0],
        ['Check they got **all the information** and could **ask questions**', 1],
        ['If not, **call the team back**', 1],
        ['Be **knowledgeable** about the treatment', 2],
        ['May be accountable for **witnessing** it: **legal age and competent**', 2]),
    ] },
  { quiz: 'w-prof', k: 'define evidence based practice', title: 'Evidence-based practice: the three parts',
    hook: 'Evidence + expertise + the patient.',
    groups: [
      G('Define it',
        ['A shift away from **opinion and past practice**', 0],
        ['… to **research and evidence** guiding decisions, to **improve patient outcomes**', 0]),
      G('It integrates',
        ['The **best research evidence**', 1],
        ['**Clinical expertise**', 1],
        ['The **patient’s values and preferences**', 2]),
    ] },
  { quiz: 'w-prof', k: 'list the five steps of the evidence', title: 'The five steps of EBP',
    hook: 'Ask, find, appraise, implement, evaluate.',
    groups: [
      G('In order',
        ['1 Develop a **research (clinical) question**', 0],
        ['2 **Find the research evidence**: **CINAHL**, **Cochrane**, PubMed', 1],
        ['3 **Appraise the evidence**: **systematic reviews** are strongest', 2],
        ['4 **Implement** the evidence **in practice**', 3],
        ['5 **Evaluate** the change: has it **made a difference**?', 4]),
    ] },
  { quiz: 'w-prof', k: 'define burnout', title: 'Burnout vs compassion fatigue',
    hook: 'Burnout: the JOB wears you out. Compassion fatigue: the CARING does.',
    groups: [
      G('Define them',
        ['**Burnout**: long-term, unmanaged **workplace stress**', 0],
        ['… **exhaustion**, **cynicism** about the job, **reduced professional efficacy**', 0],
        ['**Compassion fatigue**: exhaustion from **caring for suffering patients**', 1],
        ['… **secondary trauma**, leading to a **loss of empathy**', 1]),
      G('Two differences',
        ['Burnout: still **feels compassion**; compassion fatigue: the **ability to feel** it goes', 2],
        ['Cause: a **stressful work environment** vs **caring for others**', 2],
        ['Burnout **builds up over time**; compassion fatigue can come **straight after** trauma', 3],
        ['Compassion fatigue can hit **relationships outside work**', 3]),
    ] },
  { quiz: 'w-prof', k: 'define self care', title: 'Self-care, resilience and the link',
    hook: 'Self-care builds resilience; resilience shields you from burnout.',
    groups: [
      G('Define them',
        ['**Self-care**: **deliberate actions** for all our **health and wellbeing**', 0],
        ['**Enjoyable**, **re-energising**, **not selfish**', 0],
        ['**Resilience**: to **adapt positively to stress** and **recover quickly**', 1]),
      G('The link',
        ['**Self-care builds resilience**', 2],
        ['Resilience **protects** nurses from **burnout and compassion fatigue**', 2]),
    ] },
];
