/* New Zealand Health Strategy 2023 — THE TOOL's questions. The lecture has no Canvas quiz,
   so these were written from the lecture deck "New Zealand Health Strategy 2023 Sem2 BN2.pptx"
   (Canvas, harvested 19 Sep 2026). Every entry names the slide it was written from. */
const R = { sys: 'pop', quiz: 'a-nzhs', quizName: 'NZ Health Strategy 2023 — the tool’s questions' };
const D = 'the New Zealand Health Strategy 2023 deck, ';

export const MCQS = [
  { ...R, q: 'What are the TWO long-term goals that underpin the New Zealand Health Strategy’s vision of pae ora?',
    options: ['To shorten hospital waiting lists and to reduce overall health spending', 'To achieve health equity and to improve health outcomes for all New Zealanders', 'To train more nurses and doctors and to build more hospitals in the regions', 'To centralise health services nationally and to expand telehealth to every region'],
    correct: 1,
    why: 'Goal 1: achieve health equity — especially for Māori, Pacific, disabled and other groups who currently have poorer outcomes. Goal 2: improve health outcomes for all New Zealanders, so everyone can live longer, healthier and more independent lives.',
    src: D + 'slide 16' },
  { ...R, q: 'Which Act reformed the health system by replacing the District Health Boards with Health New Zealand?',
    options: ['The Pae Ora (Healthy Futures) Act 2022', 'The Health Practitioners Competence Assurance Act 2003', 'The New Zealand Public Health and Disability Act 2000', 'The Health and Disability Commissioner Act 1994'],
    correct: 0,
    why: 'The Pae Ora (Healthy Futures) Act 2022 replaced the DHB system with Health New Zealand (Te Whatu Ora), established the Māori Health Authority (Te Aka Whai Ora — since disestablished, 2024) and the Public Health Agency. The lecture note: the Pae Ora Act is the “how” behind the Health Strategy.',
    src: D + 'slide 6 and the speaker notes to slide 2' },
  { ...R, q: 'The NZ Health Strategy lecture separates equity from equality. Which statement describes EQUITY?',
    options: ['Everyone receives exactly the same resources', 'Services are funded according to how many people use them', 'People are given what they need in order to reach similar outcomes', 'Care is provided only to those who can show need'],
    correct: 2,
    why: 'Equality gives everyone the same resources; equity gives people what they need to achieve similar outcomes. Health equity means everyone has a fair and just opportunity to be as healthy as possible, which requires removing obstacles such as poverty and discrimination.',
    src: D + 'slide 10' },
  { ...R, q: 'Over what time span does the New Zealand Health Strategy set the direction for improving health?',
    options: ['The next three years', 'One parliamentary term', 'The next twelve months', 'The next ten years'],
    correct: 3,
    why: 'The strategy sets the direction for improving the health of all New Zealanders over the next ten years (a long-term, 5–10 year direction). The three-year document is a different one: the Government Policy Statement on Health 2024–2027.',
    src: D + 'slides 14–15 and 31' },
  { ...R, q: '“More preventive support, closer to home; a focus on the early years; parity between mental and physical health.” Which of the six priority areas is this?',
    options: ['Priority 1 — Voice at the heart of the system', 'Priority 2 — Flexible, appropriate care', 'Priority 4 — A learning culture', 'Priority 6 — Partnerships for health and wellbeing'],
    correct: 1,
    why: 'Priority 2, Flexible, appropriate care: services focused on preventing illness and delivering care closer to home, with access for the most under-served communities — preventive support, the early years, responsive primary and community services, tackling barriers to access, and parity between mental and physical health.',
    src: D + 'slide 20' },
  { ...R, q: 'Which priority area is about people and communities having greater control over the design of services and the decisions made about their care?',
    options: ['Voice at the heart of the system', 'Valuing our workforce', 'A resilient and sustainable system', 'A learning culture'],
    correct: 0,
    why: 'Priority 1, Voice at the heart of the system: recognising and responding to the voices of people and communities throughout the health system — further honouring Te Tiriti, adapting to diverse communities, including those who have been under-served, and more locally led approaches.',
    src: D + 'slide 19' },
  { ...R, q: 'The Government Policy Statement on Health 2024–2027 names three priority areas for action. Which are they?',
    options: ['Equity, partnership and protection', 'Prevention, workforce and funding', 'Access, timeliness and quality', 'Voice, learning and resilience'],
    correct: 2,
    why: 'Access (equitable access wherever a person lives), Timeliness (care when it is needed, promptly and efficiently) and Quality (safe, easy to navigate, understandable, welcoming and continuously improving — including cultural safety and the Code of Rights).',
    src: D + 'slides 31–34' },
  { ...R, q: 'Which strategy works in partnership with the New Zealand Health Strategy and is specifically the Hauora Māori strategy?',
    options: ['Te Mana Ola', 'Kia Manawanui Aotearoa', 'Te Aorerekura', 'Pae Tū'],
    correct: 3,
    why: 'Pae Tū: Hauora Māori Strategy works in partnership with the NZ Health Strategy. Te Mana Ola is the Pacific Health Strategy; Kia Manawanui Aotearoa is the mental wellbeing strategy; Te Aorerekura is the national strategy to eliminate family violence and sexual violence.',
    src: D + 'slides 11, 13 and 29–30' },
];

export const SAQS = [
  { ...R, pts: 3, q: 'Define health equity, explain how it differs from equality, and name one group the New Zealand Health Strategy prioritises for equity.',
    steps: [
      'Health equity: everyone has a fair and just opportunity to be as healthy as possible — which means removing obstacles to health such as poverty, discrimination and their consequences.',
      'Difference: equality gives everyone the SAME resources; equity gives people what they NEED in order to reach similar outcomes.',
      'Any one of: Māori · Pacific peoples · disabled people · other groups with poorer outcomes (the deck also names rural and low-income communities). In the strategy equity rests on ōritetanga from Te Tiriti o Waitangi.',
    ],
    src: D + 'slides 5, 9–10 and 16' },
  { ...R, pts: 6, q: 'List the six priority areas for change in the New Zealand Health Strategy 2023.',
    steps: [
      'Priority 1 — Voice at the heart of the system',
      'Priority 2 — Flexible, appropriate care',
      'Priority 3 — Valuing our workforce',
      'Priority 4 — A learning culture',
      'Priority 5 — A resilient and sustainable system',
      'Priority 6 — Partnerships for health and wellbeing',
    ],
    src: D + 'slides 19–27' },
  { ...R, pts: 3, q: 'Give three ways a nurse puts equity into action in everyday practice, according to the NZ Health Strategy lecture.',
    steps: [
      'Any three, one mark each. Understand the cultural, social and economic context of each patient, and notice the barriers that make it hard for them to get help.',
      'Advocate — speak up for patients who face barriers to accessing care.',
      'Practise in a culturally safe way and uphold Te Tiriti o Waitangi principles; be aware of your own unconscious bias and work to eliminate it; listen so that patients and whānau feel heard.',
    ],
    src: D + 'slides 35 and 38' },
];
